apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: codex
spec:
  description: Componentes para instalação da aplicação Codex
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

