apiVersion: builtin
kind: LabelTransformer
metadata:
  name: transformer-argocd-application-labels
labels:
  Environment: prd
fieldSpecs:
- path: metadata/labels
  create: true
- path: metadata/labels
  create: true  